//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop

#include "DBSave.h"
//---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"
TfrmDBSave *frmDBSave;
//---------------------------------------------------------------------------
__fastcall TfrmDBSave::TfrmDBSave(TComponent* Owner)
 : TForm(Owner)
{
}
//---------------------------------------------------------------------------
