//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop

#include "EditGrid.h"
//---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"
TfrmEditGrid *frmEditGrid;
//---------------------------------------------------------------------------
__fastcall TfrmEditGrid::TfrmEditGrid(TComponent* Owner)
  : TForm(Owner)
{
}
//---------------------------------------------------------------------------
