//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop

#include "ErrorFrom.h"
//---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"
TfrmError *frmError;
//---------------------------------------------------------------------------
__fastcall TfrmError::TfrmError(TComponent* Owner)
	: TForm(Owner)
{
}
//---------------------------------------------------------------------------
