//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop
USEUNIT("stackvalue.cpp");
USEUNIT("LZSS.cpp");
USEUNIT("mystream.cpp");
USEUNIT("mystring.cpp");
USEUNIT("Date.cpp");
USEUNIT("Tokenizer.cpp");
USEUNIT("Convertions.cpp");
//---------------------------------------------------------------------------
#define Library

// To add a file to the library use the Project menu 'Add to Project'.

