//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop

#include "AddObject.h"
//---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"
TfrmAddObject *frmAddObject;
//---------------------------------------------------------------------------
__fastcall TfrmAddObject::TfrmAddObject(TComponent* Owner)
  : TForm(Owner)
{

}
//---------------------------------------------------------------------------
