//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop

#include "fTaskChoose.h"
//---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"
TfrmTaskChoose *frmTaskChoose;
//---------------------------------------------------------------------------
__fastcall TfrmTaskChoose::TfrmTaskChoose(TComponent* Owner)
  : TForm(Owner)
{
}
//---------------------------------------------------------------------------

