//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop

#include <corba.h>
#include "Login.h"
//---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"
TfrmLogin *frmLogin;
//---------------------------------------------------------------------------
__fastcall TfrmLogin::TfrmLogin(TComponent* Owner)
        : TForm(Owner)
{
}


//---------------------------------------------------------------------------
