//---------------------------------------------------------------------------
#ifndef StrimComboH
#define StrimComboH
//---------------------------------------------------------------------------
#include <SysUtils.hpp>
#include <Controls.hpp>
#include <Classes.hpp>
#include <Forms.hpp>
#include "ToolEdit.hpp"
#include <Mask.hpp>
#include <StdCtrls.hpp>
#include "StreamGrid.h"

//---------------------------------------------------------------------------
class PACKAGE TStrimCombo : public TComboEdit
{
private:
protected:
public:
	__fastcall TStrimCombo(TComponent* Owner);
__published:
};
//---------------------------------------------------------------------------
#endif
